package com.voidlink.android.protocol.rtp

/**
 * Arithmetic in GF(2^8), the field every Reed-Solomon variant in this protocol uses (spec §7.7,
 * §8.4).
 *
 * The field is generated by α = 2 modulo the primitive polynomial
 * `x^8 + x^4 + x^3 + x^2 + 1` = [PRIMITIVE_POLYNOMIAL]. That polynomial is not a free choice: it is
 * the one used by the `fec.c`/`nanors`/`jerasure` family the host side descends from (spec §7.7,
 * §14), and it is also what the Backblaze-lineage implementations use, so it is the one part of the
 * FEC story that is *not* in doubt. What is in doubt is the generator matrix built on top of it —
 * see [ReedSolomonMatrix].
 *
 * Multiplication is table-driven: `a * b = α^(log a + log b)`, with the exponent table doubled in
 * length so the sum never needs a modulo.
 */
object GaloisField256 {

    /** `x^8 + x^4 + x^3 + x^2 + 1`, the field's reduction polynomial. */
    const val PRIMITIVE_POLYNOMIAL: Int = 0x11D

    /** The multiplicative group has 255 elements, so exponents are taken modulo 255. */
    const val ORDER_MINUS_ONE: Int = 255

    private val expTable = IntArray(512)
    private val logTable = IntArray(256)

    init {
        var value = 1
        for (power in 0 until ORDER_MINUS_ONE) {
            expTable[power] = value
            logTable[value] = power
            value = value shl 1
            if ((value and 0x100) != 0) value = value xor PRIMITIVE_POLYNOMIAL
        }
        for (power in ORDER_MINUS_ONE until expTable.size) {
            expTable[power] = expTable[power - ORDER_MINUS_ONE]
        }
        // log(0) is undefined; the value is never read because multiply short-circuits on zero.
        logTable[0] = 0
    }

    /** α raised to [power]; [power] must be in `0..510`. */
    fun alphaPower(power: Int): Int = expTable[power]

    /** Field product of two elements. */
    fun multiply(a: Int, b: Int): Int {
        if (a == 0 || b == 0) return 0
        return expTable[logTable[a and 0xFF] + logTable[b and 0xFF]]
    }

    /**
     * Field quotient.
     *
     * @throws IllegalArgumentException when [b] is zero — a zero pivot means the caller handed us a
     *   singular matrix, which is a bug rather than a network event.
     */
    fun divide(a: Int, b: Int): Int {
        require(b != 0) { "division by zero in GF(2^8)" }
        if (a == 0) return 0
        val difference = logTable[a and 0xFF] - logTable[b and 0xFF]
        val normalized = if (difference < 0) difference + ORDER_MINUS_ONE else difference
        return expTable[normalized]
    }

    /** Multiplicative inverse of a non-zero element. */
    fun inverse(a: Int): Int = divide(1, a)

    /**
     * [base] raised to [exponent] in the field, with `0^0 = 1`.
     *
     * Written as repeated multiplication rather than through the log table because it is called
     * only while building a generator matrix, and because `0^n` has no logarithm.
     */
    fun power(base: Int, exponent: Int): Int {
        var result = 1
        var remaining = exponent
        while (remaining > 0) {
            result = multiply(result, base)
            remaining--
        }
        return result
    }
}
