package com.voidlink.android.protocol.rtp

/**
 * Which systematic generator matrix a [ReedSolomon] instance is built from.
 *
 * **This enum is the single riskiest decision in the project** (spec §7.7, consolidated item 1).
 * Both variants below are correct erasure codes over the same field; neither can recover a shard
 * produced by the other, and the failure is silent — the recovered bytes are wrong rather than
 * missing. That is why FEC recovery is off by default and why the variant is named, swappable and
 * covered by known-answer tests rather than being an implementation detail.
 *
 * Both are built the same way: take an `n × k` Vandermonde-style matrix, invert its top `k × k`
 * block, and multiply — which makes the top of the result the identity, so the data shards pass
 * through unchanged and only the bottom `n - k` rows compute parity. The two differ only in which
 * field element generates each row.
 */
enum class ReedSolomonMatrix {

    /**
     * Row `r` is generated by α^(r-1), i.e. `V[r][c] = α^((r - 1) * c)`, with row 0 the unit
     * vector `e0`.
     *
     * The Luigi Rizzo `fec.c` construction, which `nanors` — the library `moonlight-common-c`
     * links for video FEC (spec §14) — descends from. **The default**, and the best guess at what
     * a host actually sends.
     */
    ALPHA_POWER_ROWS,

    /**
     * Row `r` is generated by the field element `r`, i.e. `V[r][c] = r^c`.
     *
     * The Backblaze `JavaReedSolomon` / `klauspost/reedsolomon` construction. Kept because it is
     * the other matrix in wide circulation, so if the default turns out to be wrong the fix is one
     * assignment rather than a rewrite. For `k = 4, p = 2` its parity rows are the widely published
     * `[27, 28, 18, 20]` and `[28, 27, 20, 18]`, which the tests assert — that published pair is
     * the only external check on this code available without a host.
     */
    INTEGER_POWER_ROWS,
}

/**
 * A systematic Reed-Solomon erasure code over GF(2^8) (spec §7.7).
 *
 * Recovers up to `parityShards` missing shards out of `dataShards + parityShards`, where every
 * shard is the same length and missing shards are marked by `null`.
 *
 * **This class is never on the critical path.** Spec §7.7 requires — and the assembler
 * implements — a reassembly path where a frame whose data shards all arrived is completed without
 * the RS code being touched at all. Recovery is attempted only when data shards are actually
 * missing, and only when [FrameAssemblerConfig.fecRecoveryEnabled] is on, which it is not by
 * default. See [UnverifiedRtpVideoConstants.FEC_RECOVERY_ENABLED_BY_DEFAULT].
 *
 * Instances are immutable and safe to share; [encodeParity] and [decodeMissing] mutate only the
 * shard array handed to them.
 */
class ReedSolomon private constructor(

    /** Number of shards carrying frame bytes. */
    val dataShards: Int,

    /** Number of parity shards computed from them. */
    val parityShards: Int,

    /** Which generator matrix this instance was built from. */
    val matrixVariant: ReedSolomonMatrix,

    private val encodeMatrix: Array<IntArray>,
) {

    /** Shards in a block: [dataShards] + [parityShards]. */
    val totalShards: Int
        get() = dataShards + parityShards

    /**
     * A row of the systematic generator matrix, as unsigned field elements.
     *
     * Exposed so tests can pin the matrix itself rather than only its behaviour — a self-consistent
     * code that uses the wrong matrix passes every round-trip test and still fails against a real
     * host.
     */
    fun matrixRow(row: Int): IntArray = encodeMatrix[row].copyOf()

    /**
     * Fills in the parity shards of [shards] from its data shards.
     *
     * Present for testing and for a future recorder; nothing in the receive path encodes.
     *
     * @param shards an array of [totalShards] entries whose first [dataShards] entries are
     *   non-null and exactly [shardSize] bytes long. Parity entries are overwritten.
     * @param shardSize the common shard length.
     */
    fun encodeParity(shards: Array<ByteArray?>, shardSize: Int) {
        require(shards.size == totalShards) {
            "expected $totalShards shards, got ${shards.size}"
        }
        for (index in 0 until dataShards) {
            val shard = requireNotNull(shards[index]) { "data shard $index is missing" }
            require(shard.size == shardSize) {
                "data shard $index is ${shard.size} bytes, expected $shardSize"
            }
        }
        val identity = IntArray(dataShards) { it }
        for (row in dataShards until totalShards) {
            shards[row] = combine(encodeMatrix[row], shards, identity, shardSize)
        }
    }

    /**
     * Reconstructs every missing **data** shard of [shards] in place.
     *
     * Parity shards are not reconstructed: nothing downstream reads them, and computing them would
     * cost work on the receive thread for no one's benefit.
     *
     * @param shards an array of [totalShards] entries; `null` marks a shard that never arrived.
     *   Every non-null entry must be exactly [shardSize] bytes — the caller zero-pads, because
     *   spec §7.7 says shards are "the same size, zero-padded as needed".
     * @param shardSize the common shard length.
     * @return true when every data shard is present afterwards; false when too few shards survived,
     *   or the input was inconsistent. False is an ordinary outcome, not an error: the caller drops
     *   the frame and requests an IDR.
     */
    fun decodeMissing(shards: Array<ByteArray?>, shardSize: Int): Boolean {
        if (shards.size != totalShards || shardSize <= 0) return false

        var missingData = 0
        for (index in 0 until dataShards) {
            if (shards[index] == null) missingData++
        }
        if (missingData == 0) return true

        val survivors = IntArray(dataShards)
        var found = 0
        for (index in 0 until totalShards) {
            val shard = shards[index] ?: continue
            if (shard.size != shardSize) return false
            if (found < dataShards) {
                survivors[found] = index
                found++
            }
        }
        if (found < dataShards) return false

        val submatrix = Array(dataShards) { encodeMatrix[survivors[it]] }
        val inverse = invert(submatrix) ?: return false

        for (row in 0 until dataShards) {
            if (shards[row] != null) continue
            shards[row] = combine(inverse[row], shards, survivors, shardSize)
        }
        return true
    }

    /**
     * Computes `sum(coefficients[i] * shards[sources[i]])` over the field, one shard's worth.
     *
     * The inner loop is the whole cost of FEC. It stays a plain byte loop rather than anything
     * clever: it runs only when a shard was actually lost.
     */
    private fun combine(
        coefficients: IntArray,
        shards: Array<ByteArray?>,
        sources: IntArray,
        shardSize: Int,
    ): ByteArray {
        val output = ByteArray(shardSize)
        for (term in 0 until dataShards) {
            val factor = coefficients[term]
            if (factor == 0) continue
            val source = shards[sources[term]] ?: continue
            for (index in 0 until shardSize) {
                val accumulated = output[index].toInt() and 0xFF
                val contribution = GaloisField256.multiply(
                    factor,
                    source[index].toInt() and 0xFF,
                )
                output[index] = (accumulated xor contribution).toByte()
            }
        }
        return output
    }

    companion object {

        /** GF(2^8) cannot address more shards than this in one block. */
        const val MAX_SHARDS: Int = RtpVideoConstants.MAX_SHARDS_PER_BLOCK

        /**
         * Builds a codec for the given geometry.
         *
         * @param dataShards at least one.
         * @param parityShards at least one.
         * @param variant which generator matrix to build; defaults to the project-wide
         *   [UnverifiedRtpVideoConstants.FEC_MATRIX_VARIANT].
         * @throws IllegalArgumentException for a geometry GF(2^8) cannot express.
         */
        fun create(
            dataShards: Int,
            parityShards: Int,
            variant: ReedSolomonMatrix = UnverifiedRtpVideoConstants.FEC_MATRIX_VARIANT,
        ): ReedSolomon {
            require(dataShards >= 1) { "dataShards must be at least 1, was $dataShards" }
            require(parityShards >= 1) { "parityShards must be at least 1, was $parityShards" }
            require(dataShards + parityShards <= MAX_SHARDS) {
                "GF(2^8) addresses at most $MAX_SHARDS shards, asked for " +
                    "${dataShards + parityShards}"
            }
            val total = dataShards + parityShards
            val raw = vandermonde(total, dataShards, variant)
            val top = Array(dataShards) { raw[it] }
            val topInverse = invert(top)
                ?: throw IllegalArgumentException(
                    "the top $dataShards x $dataShards block of the $variant matrix is singular",
                )
            val encodeMatrix = multiply(raw, topInverse)
            return ReedSolomon(dataShards, parityShards, variant, encodeMatrix)
        }

        /** Builds the raw `n × k` matrix the systematic form is derived from. */
        private fun vandermonde(
            rows: Int,
            columns: Int,
            variant: ReedSolomonMatrix,
        ): Array<IntArray> {
            val matrix = Array(rows) { IntArray(columns) }
            when (variant) {
                ReedSolomonMatrix.ALPHA_POWER_ROWS -> {
                    // Row 0 is the unit vector; it cannot come from the exponent table because
                    // α^0 = 1 for every column, which would make it a row of ones.
                    matrix[0][0] = 1
                    for (row in 1 until rows) {
                        for (column in 0 until columns) {
                            val exponent = ((row - 1) * column) % GaloisField256.ORDER_MINUS_ONE
                            matrix[row][column] = GaloisField256.alphaPower(exponent)
                        }
                    }
                }

                ReedSolomonMatrix.INTEGER_POWER_ROWS -> {
                    for (row in 0 until rows) {
                        for (column in 0 until columns) {
                            matrix[row][column] = GaloisField256.power(row, column)
                        }
                    }
                }
            }
            return matrix
        }

        /** Ordinary matrix product over GF(2^8). */
        private fun multiply(left: Array<IntArray>, right: Array<IntArray>): Array<IntArray> {
            val rows = left.size
            val inner = right.size
            val columns = right[0].size
            return Array(rows) { row ->
                IntArray(columns) { column ->
                    var sum = 0
                    for (term in 0 until inner) {
                        sum = sum xor GaloisField256.multiply(left[row][term], right[term][column])
                    }
                    sum
                }
            }
        }

        /**
         * Gauss-Jordan inversion over GF(2^8).
         *
         * Copies its input, so the rows of a shared generator matrix can be handed in directly.
         *
         * @return the inverse, or `null` when [matrix] is singular. A singular submatrix during
         *   decode would mean the surviving shard set cannot determine the lost ones, which the
         *   theory says cannot happen for a Vandermonde-derived code — but "cannot happen" is not
         *   a reason to crash the receive thread on a remote host's data.
         */
        private fun invert(matrix: Array<IntArray>): Array<IntArray>? {
            val size = matrix.size
            val work = Array(size) { row ->
                val augmented = IntArray(size * 2)
                for (column in 0 until size) augmented[column] = matrix[row][column]
                augmented[size + row] = 1
                augmented
            }

            for (column in 0 until size) {
                var pivot = -1
                for (row in column until size) {
                    if (work[row][column] != 0) {
                        pivot = row
                        break
                    }
                }
                if (pivot < 0) return null
                if (pivot != column) {
                    val swap = work[pivot]
                    work[pivot] = work[column]
                    work[column] = swap
                }

                val pivotRow = work[column]
                val scale = GaloisField256.inverse(pivotRow[column])
                for (index in 0 until size * 2) {
                    pivotRow[index] = GaloisField256.multiply(pivotRow[index], scale)
                }

                for (row in 0 until size) {
                    if (row == column) continue
                    val factor = work[row][column]
                    if (factor == 0) continue
                    val target = work[row]
                    for (index in 0 until size * 2) {
                        target[index] = target[index] xor
                            GaloisField256.multiply(factor, pivotRow[index])
                    }
                }
            }

            return Array(size) { row ->
                IntArray(size) { column -> work[row][size + column] }
            }
        }
    }
}

/**
 * Caches one [ReedSolomon] per shard geometry.
 *
 * The host changes `dataShards` and `fecPercentage` per frame (spec §7.4), so a stream sees a
 * handful of distinct geometries; building the generator matrix costs a matrix inversion and must
 * not happen per frame. The map is bounded because the geometry space is small and bounded, but
 * the bound is enforced rather than assumed.
 *
 * **Not thread-safe** — one instance per `video-rx` thread (architecture §3).
 */
class ReedSolomonCache(
    private val variant: ReedSolomonMatrix = UnverifiedRtpVideoConstants.FEC_MATRIX_VARIANT,
    private val maxEntries: Int = MAX_ENTRIES,
) {

    private val codecs = HashMap<Long, ReedSolomon>()

    /**
     * Returns a codec for the geometry, building it on first use.
     *
     * @return the codec, or `null` when the geometry is not one GF(2^8) can express, or when the
     *   cache is full of other geometries — both of which mean "do not attempt recovery".
     */
    fun get(dataShards: Int, parityShards: Int): ReedSolomon? {
        if (dataShards < 1 || parityShards < 1) return null
        if (dataShards + parityShards > ReedSolomon.MAX_SHARDS) return null
        val key = (dataShards.toLong() shl 32) or parityShards.toLong()
        val existing = codecs[key]
        if (existing != null) return existing
        if (codecs.size >= maxEntries) return null
        val created = runCatching { ReedSolomon.create(dataShards, parityShards, variant) }
            .getOrNull()
            ?: return null
        codecs[key] = created
        return created
    }

    /** Number of distinct geometries built so far. Exposed for tests and diagnostics. */
    val size: Int
        get() = codecs.size

    companion object {
        /** Generous: a stream in practice uses a handful of geometries, not dozens. */
        const val MAX_ENTRIES: Int = 32
    }
}
